title: Sean R. Abraham
description: >- # this means to ignore newlines until "baseurl:"
  Sean R. Abraham's GitHub site!
baseurl: "" # the subpath of your site, e.g. /blog
domain: srabraham.github.io
url: http://srabraham.github.io # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed

